type SummaryStripProps = {
  summaryText: string;
  isExpanded: boolean;
  shouldTruncate: boolean;
  onToggleExpanded: () => void;
};

export function SummaryStrip({
  summaryText,
  isExpanded,
  shouldTruncate,
  onToggleExpanded,
}: SummaryStripProps) {
  return (
    <section className="summary-strip mt-4 border-y border-default bg-surface-subtle px-4 py-3 sm:px-5">
      <p className="mb-1 text-[11px] uppercase tracking-wide text-muted">Generated by Cap5 AI</p>
      <p
        className="text-[13px] leading-relaxed text-secondary"
        style={
          isExpanded || !shouldTruncate
            ? undefined
            : {
                display: "-webkit-box",
                WebkitLineClamp: 3,
                WebkitBoxOrient: "vertical",
                overflow: "hidden",
              }
        }
      >
        {summaryText}
      </p>
      {shouldTruncate && (
        <button
          type="button"
          onClick={onToggleExpanded}
          className="mt-1.5 text-xs font-medium text-secondary transition-colors hover:text-foreground"
        >
          {isExpanded ? "Show less" : "Show more"}
        </button>
      )}
    </section>
  );
}
