/**
 * Compact (rail-embedded) version of SummaryCard.
 * Used inside VideoRail where the card wrapper is provided by the rail itself.
 */
import type { VideoStatusResponse } from '../lib/api';
import { useSummaryData } from './useSummaryData';

type SummaryCardCompactProps = {
  aiStatus: VideoStatusResponse['aiStatus'] | undefined;
  aiOutput: VideoStatusResponse['aiOutput'] | null | undefined;
  errorMessage: string | null | undefined;
  chapters: Array<{ title: string; seconds: number }>;
  onJumpToSeconds: (seconds: number) => void;
};

export function SummaryCardCompact({
  aiStatus,
  aiOutput,
  errorMessage,
  chapters,
  onJumpToSeconds,
}: SummaryCardCompactProps) {
  const {
    copyFeedback,
    summaryForCopy,
    copyValue,
    chapterItems,
    entitySections,
    actionItems,
    quotes,
    formatTimestamp,
  } = useSummaryData({ aiOutput, chapters });

  return (
    <div className="flex flex-col h-full">
      {/* Status messages */}
      {(aiStatus === 'queued' || aiStatus === 'processing') && (
        <p className="px-4 pt-4 text-[13px] text-secondary">
          Summary generation is in progress.
        </p>
      )}
      {aiStatus === 'not_started' && (
        <p className="px-4 pt-4 text-[13px] text-secondary">
          Summary generates after transcript completes.
        </p>
      )}
      {aiStatus === 'skipped' && (
        <p className="panel-subtle m-4 text-[13px]">
          Summary was skipped — no transcript available.
        </p>
      )}
      {aiStatus === 'failed' && (
        <p className="panel-danger m-4 text-[13px]">
          {errorMessage ? `Summary failed: ${errorMessage}` : 'Summary failed after retries.'}
        </p>
      )}
      {aiStatus === 'complete' && !aiOutput?.summary && !aiOutput?.title && (
        <p className="panel-subtle m-4 text-[13px]">
          Summary completed but no content was returned.
        </p>
      )}

      {aiStatus === 'complete' && aiOutput && (
        <div className="px-4 py-3 space-y-4">
          <p className="text-[11px] italic text-muted">Generated by Cap5 AI</p>

          {aiOutput.summary && (
            <p className="text-[13px] leading-[1.55] text-secondary">{aiOutput.summary}</p>
          )}

          {summaryForCopy && (
            <button
              type="button"
              onClick={() =>
                void copyValue(summaryForCopy, 'Summary copied', 'Unable to copy summary.')
              }
              className="btn-secondary text-[11px] px-2 py-0.5"
            >
              Copy summary
            </button>
          )}

          {chapterItems.length > 0 && (
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted">
                Chapters
              </p>
              <ol className="space-y-0 divide-y border-border-default">
                {chapterItems.map((chapter, index) => (
                  <li key={`${chapter.title}-${index}-${chapter.jumpSeconds ?? 'na'}`}>
                    <button
                      type="button"
                      onClick={() => {
                        if (chapter.jumpSeconds !== null) onJumpToSeconds(chapter.jumpSeconds);
                      }}
                      disabled={chapter.jumpSeconds === null}
                      className="summary-chapter-link flex w-full items-center gap-3 px-1 py-2 text-left transition-colors disabled:opacity-60"
                    >
                      <span className="font-mono text-[11px] w-10 shrink-0 text-muted">
                        {chapter.jumpSeconds !== null
                          ? formatTimestamp(chapter.jumpSeconds)
                          : '--:--'}
                      </span>
                      <span className="flex-1 text-[13px] leading-snug">{chapter.title}</span>
                    </button>
                  </li>
                ))}
              </ol>
            </div>
          )}

          {entitySections.length > 0 && (
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted">
                Entities
              </p>
              <div className="space-y-2">
                {entitySections.map((section) => (
                  <div key={section.label}>
                    <p className="text-[11px] font-medium text-secondary">{section.label}</p>
                    <div className="mt-1 flex flex-wrap gap-1.5">
                      {section.items.map((item) => (
                        <span
                          key={`${section.label}-${item}`}
                          className="rounded-full border px-2 py-0.5 text-[11px]"
                          style={{
                            borderColor: 'var(--border-default)',
                            color: 'var(--text-secondary)',
                          }}
                        >
                          {item}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {actionItems.length > 0 && (
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted">
                Action items
              </p>
              <ul className="space-y-2">
                {actionItems.map((item, index) => (
                  <li
                    key={`${item.task}-${index}`}
                    className="rounded-lg border px-2.5 py-2 text-[12px] border-border-default"
                  >
                    <p className="text-foreground">{item.task}</p>
                    {(item.assignee || item.deadline) && (
                      <p className="mt-1 text-[11px] text-muted">
                        {[
                          item.assignee ? `Assignee: ${item.assignee}` : null,
                          item.deadline ? `Due: ${item.deadline}` : null,
                        ]
                          .filter(Boolean)
                          .join(' • ')}
                      </p>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {quotes.length > 0 && (
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted">
                Quotes
              </p>
              <ul className="space-y-2">
                {quotes.map((quote, index) => (
                  <li
                    key={`${quote.text}-${index}`}
                    className="rounded-lg border px-2.5 py-2 text-[12px] border-border-default"
                  >
                    <p className="text-foreground">&ldquo;{quote.text}&rdquo;</p>
                    <button
                      type="button"
                      onClick={() => onJumpToSeconds(quote.timestamp)}
                      className="mt-1 text-[11px] font-medium text-blue"
                    >
                      Jump to {formatTimestamp(quote.timestamp)}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {copyFeedback && (
        <p className="px-4 pb-2 text-[11px] font-medium text-muted">{copyFeedback}</p>
      )}
    </div>
  );
}
