import { useMemo, useState } from 'react';
import type { VideoStatusResponse } from '../lib/api';
import { formatTimestamp } from '../lib/format';

type SummaryCardProps = {
  aiStatus: VideoStatusResponse['aiStatus'] | undefined;
  aiOutput: VideoStatusResponse['aiOutput'] | null | undefined;
  errorMessage: string | null | undefined;
  shareableResultUrl: string | null;
  chapters: Array<{ title: string; seconds: number }>;
  onJumpToSeconds: (seconds: number) => void;
  /** When true, omits the outer card wrapper — for embedding in the right rail */
  compact?: boolean;
};

type TimedKeyPoint = { title: string; jumpSeconds: number | null };
type EntitySection = { label: string; items: string[] };

export function SummaryCard({
  aiStatus,
  aiOutput,
  errorMessage,
  shareableResultUrl: _shareableResultUrl,
  chapters,
  onJumpToSeconds,
  compact = false,
}: SummaryCardProps) {
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null);

  const summaryForCopy = useMemo(() => {
    if (!aiOutput) return null;
    const title = aiOutput.title?.trim() ? `Title: ${aiOutput.title.trim()}` : null;
    const summary = aiOutput.summary?.trim() ? `Summary: ${aiOutput.summary.trim()}` : null;
    const points =
      aiOutput.keyPoints.length > 0
        ? `Key points:\n${aiOutput.keyPoints.map(p => `- ${p}`).join('\n')}`
        : null;
    return [title, summary, points].filter(Boolean).join('\n\n');
  }, [aiOutput]);

  const copyValue = async (value: string, successLabel: string, failureLabel: string) => {
    try {
      await navigator.clipboard.writeText(value);
      setCopyFeedback(successLabel);
    } catch {
      setCopyFeedback(failureLabel);
    }
    window.setTimeout(() => setCopyFeedback(null), 1800);
  };

  const chapterItems = useMemo<TimedKeyPoint[]>(() => {
    const usable = chapters.filter(c => Number.isFinite(c.seconds) && c.seconds >= 0);
    if (usable.length > 0) return usable.map(c => ({ title: c.title, jumpSeconds: c.seconds }));
    if (!aiOutput) return [];
    return aiOutput.keyPoints.map(p => ({ title: p, jumpSeconds: null }));
  }, [aiOutput, chapters]);

  const entitySections = useMemo<EntitySection[]>(() => {
    if (!aiOutput?.entities) return [];
    return [
      { label: 'People', items: aiOutput.entities.people },
      { label: 'Organizations', items: aiOutput.entities.organizations },
      { label: 'Locations', items: aiOutput.entities.locations },
      { label: 'Dates', items: aiOutput.entities.dates },
    ].filter(section => section.items.length > 0);
  }, [aiOutput]);

  const actionItems = aiOutput?.actionItems ?? [];
  const quotes = aiOutput?.quotes ?? [];

  /* ── Compact (rail-embedded) render ────────────────────────────────────── */
  if (compact) {
    return (
      <div className="flex flex-col h-full">
        {/* Status messages */}
        {(aiStatus === 'queued' || aiStatus === 'processing') && (
          <p className="px-4 pt-4 text-[13px] text-secondary">
            Summary generation is in progress.
          </p>
        )}
        {aiStatus === 'not_started' && (
          <p className="px-4 pt-4 text-[13px] text-secondary">
            Summary generates after transcript completes.
          </p>
        )}
        {aiStatus === 'skipped' && (
          <p className="panel-subtle m-4 text-[13px]">
            Summary was skipped — no transcript available.
          </p>
        )}
        {aiStatus === 'failed' && (
          <p className="panel-danger m-4 text-[13px]">
            {errorMessage ? `Summary failed: ${errorMessage}` : 'Summary failed after retries.'}
          </p>
        )}
        {aiStatus === 'complete' && !aiOutput?.summary && !aiOutput?.title && (
          <p className="panel-subtle m-4 text-[13px]">
            Summary completed but no content was returned.
          </p>
        )}

        {aiStatus === 'complete' && aiOutput && (
          <div className="px-4 py-3 space-y-4">
            {/* Generated by label */}
            <p className="text-[11px] italic text-muted">
              Generated by Cap AI
            </p>

            {/* Summary text */}
            {aiOutput.summary && (
              <p className="text-[13px] leading-[1.55] text-secondary">
                {aiOutput.summary}
              </p>
            )}

            {/* Copy action */}
            {summaryForCopy && (
              <button
                type="button"
                onClick={() =>
                  void copyValue(summaryForCopy, 'Summary copied', 'Unable to copy summary.')
                }
                className="btn-secondary text-[11px] px-2 py-0.5"
              >
                Copy summary
              </button>
            )}

            {/* Chapters in summary tab */}
            {chapterItems.length > 0 && (
              <div>
                <p
                  className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted"
                  
                >
                  Chapters
                </p>
                <ol className="space-y-0 divide-y border-border-default">
                  {chapterItems.map((chapter, index) => (
                    <li key={`${chapter.title}-${index}-${chapter.jumpSeconds ?? 'na'}`}>
                      <button
                        type="button"
                        onClick={() => {
                          if (chapter.jumpSeconds !== null) onJumpToSeconds(chapter.jumpSeconds);
                        }}
                        disabled={chapter.jumpSeconds === null}
                        className="summary-chapter-link flex w-full items-center gap-3 px-1 py-2 text-left transition-colors disabled:opacity-60"
                      >
                        <span
                          className="font-mono text-[11px] w-10 shrink-0 text-muted"
                          
                        >
                          {chapter.jumpSeconds !== null
                            ? formatTimestamp(chapter.jumpSeconds)
                            : '--:--'}
                        </span>
                        <span className="flex-1 text-[13px] leading-snug">{chapter.title}</span>
                      </button>
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {entitySections.length > 0 && (
              <div>
                <p
                  className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted"
                  
                >
                  Entities
                </p>
                <div className="space-y-2">
                  {entitySections.map(section => (
                    <div key={section.label}>
                      <p className="text-[11px] font-medium text-secondary">
                        {section.label}
                      </p>
                      <div className="mt-1 flex flex-wrap gap-1.5">
                        {section.items.map(item => (
                          <span
                            key={`${section.label}-${item}`}
                            className="rounded-full border px-2 py-0.5 text-[11px]"
                            style={{ borderColor: 'var(--border-default)', color: 'var(--text-secondary)' }}
                          >
                            {item}
                          </span>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {actionItems.length > 0 && (
              <div>
                <p
                  className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted"
                  
                >
                  Action items
                </p>
                <ul className="space-y-2">
                  {actionItems.map((item, index) => (
                    <li key={`${item.task}-${index}`} className="rounded-lg border px-2.5 py-2 text-[12px] border-border-default">
                      <p className="text-foreground">{item.task}</p>
                      {(item.assignee || item.deadline) && (
                        <p className="mt-1 text-[11px] text-muted">
                          {[item.assignee ? `Assignee: ${item.assignee}` : null, item.deadline ? `Due: ${item.deadline}` : null].filter(Boolean).join(' • ')}
                        </p>
                      )}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {quotes.length > 0 && (
              <div>
                <p
                  className="text-[11px] font-semibold uppercase tracking-wide mb-2 text-muted"
                  
                >
                  Quotes
                </p>
                <ul className="space-y-2">
                  {quotes.map((quote, index) => (
                    <li key={`${quote.text}-${index}`} className="rounded-lg border px-2.5 py-2 text-[12px] border-border-default">
                      <p className="text-foreground">&ldquo;{quote.text}&rdquo;</p>
                      <button
                        type="button"
                        onClick={() => onJumpToSeconds(quote.timestamp)}
                        className="mt-1 text-[11px] font-medium text-blue"
                        
                      >
                        Jump to {formatTimestamp(quote.timestamp)}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {copyFeedback && (
          <p className="px-4 pb-2 text-[11px] font-medium text-muted">
            {copyFeedback}
          </p>
        )}
      </div>
    );
  }

  /* ── Full standalone card render ────────────────────────────────────────── */
  const Inner = (
    <div>
      <div className="mb-3 flex items-center justify-between gap-2">
        <div>
          <p className="workspace-label">Summary</p>
          <h2 className="workspace-title">Summary and Chapters</h2>
        </div>
        <span className="status-chip">{aiStatus ?? 'not_started'}</span>
      </div>

      {(aiStatus === 'queued' || aiStatus === 'processing') && (
        <p className="text-sm text-hint">Summary generation is in progress.</p>
      )}
      {aiStatus === 'not_started' && (
        <p className="text-sm text-hint">Summary generation starts after transcript completion.</p>
      )}
      {aiStatus === 'skipped' && (
        <p className="panel-subtle">
          Summary was skipped because transcript input was not available.
        </p>
      )}
      {aiStatus === 'failed' && (
        <p className="panel-danger">
          {errorMessage ? `Summary failed: ${errorMessage}` : 'Summary failed after retries.'}
        </p>
      )}
      {aiStatus === 'complete' && !aiOutput?.summary && !aiOutput?.title && (
        <p className="panel-subtle">Summary completed, but no content was returned.</p>
      )}

      {aiStatus === 'complete' && aiOutput && (
        <div className="space-y-4">
          <div className="flex flex-wrap gap-2">
            {summaryForCopy && (
              <button
                type="button"
                onClick={() =>
                  void copyValue(summaryForCopy, 'Summary copied', 'Unable to copy summary.')
                }
                className="btn-secondary text-xs px-2.5 py-1"
              >
                Copy summary
              </button>
            )}
          </div>
          {aiOutput.title && <h3 className="text-xl font-semibold">{aiOutput.title}</h3>}
          {aiOutput.summary && (
            <p className="panel-subtle rounded-lg px-4 py-3 text-sm leading-relaxed">
              {aiOutput.summary}
            </p>
          )}
          {chapterItems.length > 0 && (
            <div className="space-y-1">
              <p
                className="text-xs font-semibold uppercase tracking-wide mb-2 text-muted"
                
              >
                Chapters
              </p>
              <ol className="space-y-1">
                {chapterItems.map((chapter, index) => (
                  <li key={`${chapter.title}-${index}-${chapter.jumpSeconds ?? 'na'}`}>
                    <button
                      type="button"
                      onClick={() => {
                        if (chapter.jumpSeconds !== null) onJumpToSeconds(chapter.jumpSeconds);
                      }}
                      disabled={chapter.jumpSeconds === null}
                      className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left transition hover:bg-surface-muted disabled:opacity-60"
                    >
                      <span
                        className="font-mono text-xs w-12 shrink-0 text-muted"
                        
                      >
                        {chapter.jumpSeconds !== null
                          ? formatTimestamp(chapter.jumpSeconds)
                          : '--:--'}
                      </span>
                      <span className="flex-1 text-sm leading-snug">{chapter.title}</span>
                    </button>
                  </li>
                ))}
              </ol>
            </div>
          )}
          {entitySections.length > 0 && (
            <div className="space-y-2">
              <p
                className="text-xs font-semibold uppercase tracking-wide mb-2 text-muted"
                
              >
                Entities
              </p>
              {entitySections.map(section => (
                <div key={section.label}>
                  <p className="text-xs font-medium text-secondary">
                    {section.label}
                  </p>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {section.items.map(item => (
                      <span
                        key={`${section.label}-${item}`}
                        className="rounded-full border px-2 py-0.5 text-xs"
                        style={{ borderColor: 'var(--border-default)', color: 'var(--text-secondary)' }}
                      >
                        {item}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
          {actionItems.length > 0 && (
            <div className="space-y-2">
              <p
                className="text-xs font-semibold uppercase tracking-wide mb-2 text-muted"
                
              >
                Action items
              </p>
              <ul className="space-y-2">
                {actionItems.map((item, index) => (
                  <li
                    key={`${item.task}-${index}`}
                    className="rounded-lg border px-3 py-2 text-sm border-border-default"
                    
                  >
                    <p>{item.task}</p>
                    {(item.assignee || item.deadline) && (
                      <p className="mt-1 text-xs text-muted">
                        {[item.assignee ? `Assignee: ${item.assignee}` : null, item.deadline ? `Due: ${item.deadline}` : null].filter(Boolean).join(' • ')}
                      </p>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {quotes.length > 0 && (
            <div className="space-y-2">
              <p
                className="text-xs font-semibold uppercase tracking-wide mb-2 text-muted"
                
              >
                Quotes
              </p>
              <ul className="space-y-2">
                {quotes.map((quote, index) => (
                  <li
                    key={`${quote.text}-${index}`}
                    className="rounded-lg border px-3 py-2 text-sm border-border-default"
                    
                  >
                    <p>&ldquo;{quote.text}&rdquo;</p>
                    <button
                      type="button"
                      onClick={() => onJumpToSeconds(quote.timestamp)}
                      className="mt-1 text-xs font-medium text-blue"
                      
                    >
                      Jump to {formatTimestamp(quote.timestamp)}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
      {copyFeedback && (
        <p className="mt-3 text-xs font-medium text-muted">
          {copyFeedback}
        </p>
      )}
    </div>
  );

  return <section className="workspace-card">{Inner}</section>;
}
