import { test, expect } from "@playwright/test";
import { mockApiRoutes, MOCK_VIDEO_ID } from "./mock-api";

const VIDEO_URL = `/video/${MOCK_VIDEO_ID}`;

test.describe("Responsive layout", () => {
  test.beforeEach(async ({ page }) => {
    await mockApiRoutes(page);
  });

  test("desktop watch page exposes the current primary workflow", async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto(VIDEO_URL);
    await page.waitForLoadState("networkidle");

    await expect(
      page.getByRole("heading", { name: "Building APIs: Architecture and Best Practices", exact: true })
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Notes", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Summary", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Transcript", exact: true })).toBeVisible();
    await expect(page.getByText("Generated by Cap5 AI")).toBeVisible();
    await expect(page.getByRole("heading", { name: "Chapters", exact: true })).toBeVisible();
  });

  test("mobile watch page keeps the current content reachable", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto(VIDEO_URL);
    await page.waitForLoadState("networkidle");

    await expect(page.getByRole("link", { name: "Cap5" })).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Building APIs: Architecture and Best Practices", exact: true })
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Transcript", exact: true })).toBeVisible();

    await page.getByRole("button").nth(1).click();
    await expect(page.getByRole("link", { name: "Home" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Record" })).toBeVisible();
  });
});

test.describe("Home page", () => {
  test.beforeEach(async ({ page }) => {
    await mockApiRoutes(page);
  });

  test("home page renders provider status and the mocked library card", async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    await expect(page.getByRole("heading", { name: "Your Videos" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Library" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "System provider status" })).toBeVisible();
    await expect(page.getByText("Building APIs: Architecture and Best Practices")).toBeVisible();
  });

  test("command palette opens from the keyboard and can navigate to record", async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    await page.keyboard.press("Control+k");

    await expect(page.getByRole("dialog", { name: "Command palette" })).toBeVisible();
    await expect(page.getByLabel("Search commands")).toBeFocused();

    await page.getByLabel("Search commands").fill("record");
    await page.getByRole("button", { name: "Go to Record Start or upload a recording" }).click();

    await expect(page).toHaveURL(/\/record$/);
    await expect(page.getByRole("heading", { name: "Record or upload" })).toBeVisible();
  });

  test("shortcuts overlay opens from the keyboard and lists the shipped shortcuts", async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    await page.evaluate(() => {
      window.dispatchEvent(new KeyboardEvent("keydown", { key: "?", bubbles: true }));
    });

    const dialog = page.getByRole("dialog", { name: "Keyboard shortcuts" });
    await expect(dialog).toBeVisible();
    await expect(dialog.getByText("Cmd/Ctrl + K")).toBeVisible();
    await expect(dialog.getByText("G H")).toBeVisible();
    await expect(dialog.getByText("Space / K")).toBeVisible();

    await page.keyboard.press("Escape");
    await expect(dialog).toBeHidden();
  });
});
