import { test, expect } from "@playwright/test";
import { mockApiRoutes, MOCK_VIDEO_ID } from "./mock-api";

const VIDEO_URL = `/video/${MOCK_VIDEO_ID}`;

test.describe("Video watch page", () => {
  test.beforeEach(async ({ page }) => {
    await mockApiRoutes(page);
    await page.setViewportSize({ width: 1280, height: 800 });
  });

  test("renders the transcript workspace by default", async ({ page }) => {
    await page.goto(VIDEO_URL);
    await page.waitForLoadState("networkidle");

    await expect(page.getByRole("button", { name: "Transcript", exact: true })).toHaveClass(/rail-tab-active/);
    await expect(page.getByPlaceholder("Search transcript…")).toBeVisible();
    await expect(page.getByRole("button", { name: "Current", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Original", exact: true })).toBeVisible();
    await expect(page.getByText("Today we cover API architecture.")).toBeVisible();
  });

  test("summary tab shows AI summary copy and jumpable chapter list", async ({ page }) => {
    await page.goto(VIDEO_URL);
    await page.waitForLoadState("networkidle");

    await page.getByRole("button", { name: "Summary", exact: true }).click();

    const summaryPanel = page.locator(".rail-tab-panel-enter").filter({
      has: page.getByText("Generated by Cap5 AI"),
    });

    await expect(summaryPanel).toBeVisible();
    await expect(summaryPanel.getByText("core concepts of API architecture")).toBeVisible();
    await expect(summaryPanel.getByRole("button", { name: /00:20 Define endpoints clearly/i })).toBeVisible();
    await expect(summaryPanel.getByRole("button", { name: /00:44 Rate limiting/i })).toBeVisible();
    await expect(summaryPanel.getByText("Entities")).toBeVisible();
    await expect(summaryPanel.getByText("Review the staging deploy")).toBeVisible();
    await expect(summaryPanel.getByRole("button", { name: /Jump to 00:52/i })).toBeVisible();
  });

  test("below-the-fold chapter navigation reflects the shipped inline list", async ({ page }) => {
    await page.goto(VIDEO_URL);
    await page.waitForLoadState("networkidle");

    const chapterSection = page.locator("div.mt-5").filter({
      has: page.getByRole("heading", { name: "Chapters", exact: true }),
    });

    await expect(chapterSection).toBeVisible();
    await expect(chapterSection.getByRole("button")).toHaveCount(4);
    await expect(chapterSection.getByRole("button", { name: /00:20 define endpoints clearly/i })).toBeVisible();
    await expect(chapterSection.getByRole("button", { name: /rate limiting/i })).toBeVisible();
  });
});
